### ISSUE TITLE
Add a "last modified" date to blog posts and portfolio

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/gfsc-v3#178] opened 2023-01-23 14:52 UTC
I think this is really useful and relevant info esp if we are going to try and keep on top of them

Looks like it's doable with Git

https://mertbakir.gitlab.io/hugo/last-modified-date-in-hugo/

**Comment by ivan-kocienski-gfsc** [comment] 2023-06-29 09:50
This is a duplicate of https://github.com/geeksforsocialchange/gfsc-v3/issues/74

**Closed by ivan-kocienski-gfsc** 2023-06-29 09:50 UTC

**Comment by kimadactyl** [comment] 2023-06-30 11:59
A semi dupe, but this one mentions portfolio too.
