### ISSUE TITLE
[Bug]: Image in "everything is connected" piece not properly ported

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/gfsc-v3#223] opened 2023-03-05 18:27 UTC
https://gfsc.studio/blog/2021/everything-is-connected/

This is still visible:

```
{{ include image.html description=“Fig 2. In Gattaca (1997), finger prick blood tests are used to discriminate against those with ‘inferior’ non-genetically enhanced DNA.” url="/assets/images/blog/everything-is-connected/gattaca.jpg" class=“frame” }}
```

**Comment by aaaaargZombies** [comment] 2023-06-26 10:49
duplicate of #233  which has an open PR to resolve

**Closed by aaaaargZombies** 2023-06-26 10:49 UTC
Labels: bug
